Repository databrickslabs/dqx, pull requests merged in 2025-01, with the labels that each got.

#83 add OIDC codecov
  .github/workflows/push.yml
Labels: internal

#119 added search for docs
  Makefile
  docs/dqx/docs/dev/docs_authoring.mdx
  docs/dqx/docusaurus.config.ts
  docs/dqx/package.json
  docs/dqx/src/css/custom.css
  docs/dqx/yarn.lock
Labels: documentation

#133 New dashboard query, Update to demos and docs
  demos/dqx_demo_library.py
  demos/dqx_demo_tool.py
  docs/dqx/docs/demos.mdx
  docs/dqx/docs/guide.mdx
  docs/dqx/docs/installation.mdx
  docs/dqx/docs/motivation.mdx
  docs/dqx/docs/reference.mdx
  src/databricks/labs/dqx/installer/install.py
  src/databricks/labs/dqx/queries/quality/dashboard/00_1_dq_summary.sql
  src/databricks/labs/dqx/queries/quality/dashboard/00_2_dq_error_types.sql
  src/databricks/labs/dqx/queries/quality/dashboard/dashboard.yml
  tests/integration/test_installation.py
  tests/integration/test_load_checks_from_file.py
  tests/integration/test_save_checks_to_file.py
  tests/unit/conftest.py
  tests/unit/test_load_checks_from_local_file.py
  tests/unit/test_save_checks_in_local_file.py
  tests/unit/test_utils.py
Labels: do-not-merge

#142 Support datetime arguments for column range functions
  src/databricks/labs/dqx/col_functions.py
  tests/integration/test_functions.py
Labels: enhancement

#144 Add column functions to check for valid date strings
  src/databricks/labs/dqx/col_functions.py
  tests/integration/test_functions.py
Labels: enhancement
